@business_url = http://192.168.100.239:8000

# @name token
POST {{business_url}}/token
Content-Type: application/x-www-form-urlencoded

username=admin
&password=P@ssword123!!
###
@accessToken = {{token.response.body.$.access_token}}

